ALTER TABLE jobs ADD COLUMN runner TEXT NOT NULL DEFAULT 'docker';
ALTER TABLE jobs ADD COLUMN source_mode TEXT NOT NULL DEFAULT 'workspace';
ALTER TABLE jobs ADD COLUMN snapshot_ref TEXT NOT NULL DEFAULT '';
ALTER TABLE jobs ADD COLUMN command_args TEXT NOT NULL DEFAULT '[]';
ALTER TABLE jobs ADD COLUMN artifact_paths TEXT NOT NULL DEFAULT '[]';
ALTER TABLE jobs ADD COLUMN image TEXT NOT NULL DEFAULT '';
ALTER TABLE jobs ADD COLUMN error TEXT NOT NULL DEFAULT '';
ALTER TABLE jobs ADD COLUMN owner TEXT NOT NULL DEFAULT '';
