// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: proto/v1/service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RemoteServiceService_StartService_FullMethodName   = "/packets.v1.RemoteServiceService/StartService"
	RemoteServiceService_StopService_FullMethodName    = "/packets.v1.RemoteServiceService/StopService"
	RemoteServiceService_RestartService_FullMethodName = "/packets.v1.RemoteServiceService/RestartService"
	RemoteServiceService_ListServices_FullMethodName   = "/packets.v1.RemoteServiceService/ListServices"
	RemoteServiceService_GetServiceLogs_FullMethodName = "/packets.v1.RemoteServiceService/GetServiceLogs"
)

// RemoteServiceServiceClient is the client API for RemoteServiceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RemoteServiceServiceClient interface {
	StartService(ctx context.Context, in *StartServiceRequest, opts ...grpc.CallOption) (*ServiceResponse, error)
	StopService(ctx context.Context, in *StopServiceRequest, opts ...grpc.CallOption) (*ServiceResponse, error)
	RestartService(ctx context.Context, in *RestartServiceRequest, opts ...grpc.CallOption) (*ServiceResponse, error)
	ListServices(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ListServicesResponse, error)
	GetServiceLogs(ctx context.Context, in *GetServiceLogsRequest, opts ...grpc.CallOption) (*GetServiceLogsResponse, error)
}

type remoteServiceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRemoteServiceServiceClient(cc grpc.ClientConnInterface) RemoteServiceServiceClient {
	return &remoteServiceServiceClient{cc}
}

func (c *remoteServiceServiceClient) StartService(ctx context.Context, in *StartServiceRequest, opts ...grpc.CallOption) (*ServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceResponse)
	err := c.cc.Invoke(ctx, RemoteServiceService_StartService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remoteServiceServiceClient) StopService(ctx context.Context, in *StopServiceRequest, opts ...grpc.CallOption) (*ServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceResponse)
	err := c.cc.Invoke(ctx, RemoteServiceService_StopService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remoteServiceServiceClient) RestartService(ctx context.Context, in *RestartServiceRequest, opts ...grpc.CallOption) (*ServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceResponse)
	err := c.cc.Invoke(ctx, RemoteServiceService_RestartService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remoteServiceServiceClient) ListServices(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ListServicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListServicesResponse)
	err := c.cc.Invoke(ctx, RemoteServiceService_ListServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remoteServiceServiceClient) GetServiceLogs(ctx context.Context, in *GetServiceLogsRequest, opts ...grpc.CallOption) (*GetServiceLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServiceLogsResponse)
	err := c.cc.Invoke(ctx, RemoteServiceService_GetServiceLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RemoteServiceServiceServer is the server API for RemoteServiceService service.
// All implementations must embed UnimplementedRemoteServiceServiceServer
// for forward compatibility.
type RemoteServiceServiceServer interface {
	StartService(context.Context, *StartServiceRequest) (*ServiceResponse, error)
	StopService(context.Context, *StopServiceRequest) (*ServiceResponse, error)
	RestartService(context.Context, *RestartServiceRequest) (*ServiceResponse, error)
	ListServices(context.Context, *ListServicesRequest) (*ListServicesResponse, error)
	GetServiceLogs(context.Context, *GetServiceLogsRequest) (*GetServiceLogsResponse, error)
	mustEmbedUnimplementedRemoteServiceServiceServer()
}

// UnimplementedRemoteServiceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRemoteServiceServiceServer struct{}

func (UnimplementedRemoteServiceServiceServer) StartService(context.Context, *StartServiceRequest) (*ServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartService not implemented")
}
func (UnimplementedRemoteServiceServiceServer) StopService(context.Context, *StopServiceRequest) (*ServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopService not implemented")
}
func (UnimplementedRemoteServiceServiceServer) RestartService(context.Context, *RestartServiceRequest) (*ServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestartService not implemented")
}
func (UnimplementedRemoteServiceServiceServer) ListServices(context.Context, *ListServicesRequest) (*ListServicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListServices not implemented")
}
func (UnimplementedRemoteServiceServiceServer) GetServiceLogs(context.Context, *GetServiceLogsRequest) (*GetServiceLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetServiceLogs not implemented")
}
func (UnimplementedRemoteServiceServiceServer) mustEmbedUnimplementedRemoteServiceServiceServer() {}
func (UnimplementedRemoteServiceServiceServer) testEmbeddedByValue()                              {}

// UnsafeRemoteServiceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RemoteServiceServiceServer will
// result in compilation errors.
type UnsafeRemoteServiceServiceServer interface {
	mustEmbedUnimplementedRemoteServiceServiceServer()
}

func RegisterRemoteServiceServiceServer(s grpc.ServiceRegistrar, srv RemoteServiceServiceServer) {
	// If the following call panics, it indicates UnimplementedRemoteServiceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RemoteServiceService_ServiceDesc, srv)
}

func _RemoteServiceService_StartService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteServiceServiceServer).StartService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemoteServiceService_StartService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteServiceServiceServer).StartService(ctx, req.(*StartServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemoteServiceService_StopService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteServiceServiceServer).StopService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemoteServiceService_StopService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteServiceServiceServer).StopService(ctx, req.(*StopServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemoteServiceService_RestartService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestartServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteServiceServiceServer).RestartService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemoteServiceService_RestartService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteServiceServiceServer).RestartService(ctx, req.(*RestartServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemoteServiceService_ListServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteServiceServiceServer).ListServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemoteServiceService_ListServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteServiceServiceServer).ListServices(ctx, req.(*ListServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemoteServiceService_GetServiceLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteServiceServiceServer).GetServiceLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemoteServiceService_GetServiceLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteServiceServiceServer).GetServiceLogs(ctx, req.(*GetServiceLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RemoteServiceService_ServiceDesc is the grpc.ServiceDesc for RemoteServiceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RemoteServiceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "packets.v1.RemoteServiceService",
	HandlerType: (*RemoteServiceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartService",
			Handler:    _RemoteServiceService_StartService_Handler,
		},
		{
			MethodName: "StopService",
			Handler:    _RemoteServiceService_StopService_Handler,
		},
		{
			MethodName: "RestartService",
			Handler:    _RemoteServiceService_RestartService_Handler,
		},
		{
			MethodName: "ListServices",
			Handler:    _RemoteServiceService_ListServices_Handler,
		},
		{
			MethodName: "GetServiceLogs",
			Handler:    _RemoteServiceService_GetServiceLogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/v1/service.proto",
}
