// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: proto/v1/service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SubspaceId    string                 `protobuf:"bytes,2,opt,name=subspace_id,json=subspaceId,proto3" json:"subspace_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	Command       []string               `protobuf:"bytes,5,rep,name=command,proto3" json:"command,omitempty"`
	Environment   map[string]string      `protobuf:"bytes,6,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Ports         []string               `protobuf:"bytes,7,rep,name=ports,proto3" json:"ports,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	Driver        string                 `protobuf:"bytes,9,opt,name=driver,proto3" json:"driver,omitempty"`
	ContainerId   string                 `protobuf:"bytes,10,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceRecord) Reset() {
	*x = ServiceRecord{}
	mi := &file_proto_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceRecord) ProtoMessage() {}

func (x *ServiceRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceRecord.ProtoReflect.Descriptor instead.
func (*ServiceRecord) Descriptor() ([]byte, []int) {
	return file_proto_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServiceRecord) GetSubspaceId() string {
	if x != nil {
		return x.SubspaceId
	}
	return ""
}

func (x *ServiceRecord) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceRecord) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ServiceRecord) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ServiceRecord) GetEnvironment() map[string]string {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *ServiceRecord) GetPorts() []string {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *ServiceRecord) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ServiceRecord) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *ServiceRecord) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ServiceRecord) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ServiceRecord) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type StartServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubspaceId    string                 `protobuf:"bytes,1,opt,name=subspace_id,json=subspaceId,proto3" json:"subspace_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Command       []string               `protobuf:"bytes,4,rep,name=command,proto3" json:"command,omitempty"`
	Environment   map[string]string      `protobuf:"bytes,5,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Ports         []string               `protobuf:"bytes,6,rep,name=ports,proto3" json:"ports,omitempty"`
	Driver        string                 `protobuf:"bytes,7,opt,name=driver,proto3" json:"driver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartServiceRequest) Reset() {
	*x = StartServiceRequest{}
	mi := &file_proto_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartServiceRequest) ProtoMessage() {}

func (x *StartServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartServiceRequest.ProtoReflect.Descriptor instead.
func (*StartServiceRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *StartServiceRequest) GetSubspaceId() string {
	if x != nil {
		return x.SubspaceId
	}
	return ""
}

func (x *StartServiceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StartServiceRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *StartServiceRequest) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *StartServiceRequest) GetEnvironment() map[string]string {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *StartServiceRequest) GetPorts() []string {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *StartServiceRequest) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

type StopServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubspaceId    string                 `protobuf:"bytes,1,opt,name=subspace_id,json=subspaceId,proto3" json:"subspace_id,omitempty"`
	NameOrId      string                 `protobuf:"bytes,2,opt,name=name_or_id,json=nameOrId,proto3" json:"name_or_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopServiceRequest) Reset() {
	*x = StopServiceRequest{}
	mi := &file_proto_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopServiceRequest) ProtoMessage() {}

func (x *StopServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopServiceRequest.ProtoReflect.Descriptor instead.
func (*StopServiceRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *StopServiceRequest) GetSubspaceId() string {
	if x != nil {
		return x.SubspaceId
	}
	return ""
}

func (x *StopServiceRequest) GetNameOrId() string {
	if x != nil {
		return x.NameOrId
	}
	return ""
}

type RestartServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubspaceId    string                 `protobuf:"bytes,1,opt,name=subspace_id,json=subspaceId,proto3" json:"subspace_id,omitempty"`
	NameOrId      string                 `protobuf:"bytes,2,opt,name=name_or_id,json=nameOrId,proto3" json:"name_or_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartServiceRequest) Reset() {
	*x = RestartServiceRequest{}
	mi := &file_proto_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartServiceRequest) ProtoMessage() {}

func (x *RestartServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartServiceRequest.ProtoReflect.Descriptor instead.
func (*RestartServiceRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *RestartServiceRequest) GetSubspaceId() string {
	if x != nil {
		return x.SubspaceId
	}
	return ""
}

func (x *RestartServiceRequest) GetNameOrId() string {
	if x != nil {
		return x.NameOrId
	}
	return ""
}

type ListServicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubspaceId    string                 `protobuf:"bytes,1,opt,name=subspace_id,json=subspaceId,proto3" json:"subspace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesRequest) Reset() {
	*x = ListServicesRequest{}
	mi := &file_proto_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesRequest) ProtoMessage() {}

func (x *ListServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesRequest.ProtoReflect.Descriptor instead.
func (*ListServicesRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListServicesRequest) GetSubspaceId() string {
	if x != nil {
		return x.SubspaceId
	}
	return ""
}

type ListServicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*ServiceRecord       `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesResponse) Reset() {
	*x = ListServicesResponse{}
	mi := &file_proto_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesResponse) ProtoMessage() {}

func (x *ListServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesResponse.ProtoReflect.Descriptor instead.
func (*ListServicesResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListServicesResponse) GetServices() []*ServiceRecord {
	if x != nil {
		return x.Services
	}
	return nil
}

type GetServiceLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubspaceId    string                 `protobuf:"bytes,1,opt,name=subspace_id,json=subspaceId,proto3" json:"subspace_id,omitempty"`
	NameOrId      string                 `protobuf:"bytes,2,opt,name=name_or_id,json=nameOrId,proto3" json:"name_or_id,omitempty"`
	Lines         int32                  `protobuf:"varint,3,opt,name=lines,proto3" json:"lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceLogsRequest) Reset() {
	*x = GetServiceLogsRequest{}
	mi := &file_proto_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceLogsRequest) ProtoMessage() {}

func (x *GetServiceLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceLogsRequest.ProtoReflect.Descriptor instead.
func (*GetServiceLogsRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetServiceLogsRequest) GetSubspaceId() string {
	if x != nil {
		return x.SubspaceId
	}
	return ""
}

func (x *GetServiceLogsRequest) GetNameOrId() string {
	if x != nil {
		return x.NameOrId
	}
	return ""
}

func (x *GetServiceLogsRequest) GetLines() int32 {
	if x != nil {
		return x.Lines
	}
	return 0
}

type GetServiceLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          string                 `protobuf:"bytes,1,opt,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceLogsResponse) Reset() {
	*x = GetServiceLogsResponse{}
	mi := &file_proto_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceLogsResponse) ProtoMessage() {}

func (x *GetServiceLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceLogsResponse.ProtoReflect.Descriptor instead.
func (*GetServiceLogsResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetServiceLogsResponse) GetLogs() string {
	if x != nil {
		return x.Logs
	}
	return ""
}

type ServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       *ServiceRecord         `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceResponse) Reset() {
	*x = ServiceResponse{}
	mi := &file_proto_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceResponse) ProtoMessage() {}

func (x *ServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceResponse.ProtoReflect.Descriptor instead.
func (*ServiceResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_service_proto_rawDescGZIP(), []int{8}
}

func (x *ServiceResponse) GetService() *ServiceRecord {
	if x != nil {
		return x.Service
	}
	return nil
}

var File_proto_v1_service_proto protoreflect.FileDescriptor

const file_proto_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x16proto/v1/service.proto\x12\n" +
	"packets.v1\"\xb9\x03\n" +
	"\rServiceRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vsubspace_id\x18\x02 \x01(\tR\n" +
	"subspaceId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x04 \x01(\tR\x05image\x12\x18\n" +
	"\acommand\x18\x05 \x03(\tR\acommand\x12L\n" +
	"\venvironment\x18\x06 \x03(\v2*.packets.v1.ServiceRecord.EnvironmentEntryR\venvironment\x12\x14\n" +
	"\x05ports\x18\a \x03(\tR\x05ports\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x16\n" +
	"\x06driver\x18\t \x01(\tR\x06driver\x12!\n" +
	"\fcontainer_id\x18\n" +
	" \x01(\tR\vcontainerId\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\tR\tupdatedAt\x1a>\n" +
	"\x10EnvironmentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbc\x02\n" +
	"\x13StartServiceRequest\x12\x1f\n" +
	"\vsubspace_id\x18\x01 \x01(\tR\n" +
	"subspaceId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x18\n" +
	"\acommand\x18\x04 \x03(\tR\acommand\x12R\n" +
	"\venvironment\x18\x05 \x03(\v20.packets.v1.StartServiceRequest.EnvironmentEntryR\venvironment\x12\x14\n" +
	"\x05ports\x18\x06 \x03(\tR\x05ports\x12\x16\n" +
	"\x06driver\x18\a \x01(\tR\x06driver\x1a>\n" +
	"\x10EnvironmentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"S\n" +
	"\x12StopServiceRequest\x12\x1f\n" +
	"\vsubspace_id\x18\x01 \x01(\tR\n" +
	"subspaceId\x12\x1c\n" +
	"\n" +
	"name_or_id\x18\x02 \x01(\tR\bnameOrId\"V\n" +
	"\x15RestartServiceRequest\x12\x1f\n" +
	"\vsubspace_id\x18\x01 \x01(\tR\n" +
	"subspaceId\x12\x1c\n" +
	"\n" +
	"name_or_id\x18\x02 \x01(\tR\bnameOrId\"6\n" +
	"\x13ListServicesRequest\x12\x1f\n" +
	"\vsubspace_id\x18\x01 \x01(\tR\n" +
	"subspaceId\"M\n" +
	"\x14ListServicesResponse\x125\n" +
	"\bservices\x18\x01 \x03(\v2\x19.packets.v1.ServiceRecordR\bservices\"l\n" +
	"\x15GetServiceLogsRequest\x12\x1f\n" +
	"\vsubspace_id\x18\x01 \x01(\tR\n" +
	"subspaceId\x12\x1c\n" +
	"\n" +
	"name_or_id\x18\x02 \x01(\tR\bnameOrId\x12\x14\n" +
	"\x05lines\x18\x03 \x01(\x05R\x05lines\",\n" +
	"\x16GetServiceLogsResponse\x12\x12\n" +
	"\x04logs\x18\x01 \x01(\tR\x04logs\"F\n" +
	"\x0fServiceResponse\x123\n" +
	"\aservice\x18\x01 \x01(\v2\x19.packets.v1.ServiceRecordR\aservice2\xae\x03\n" +
	"\x14RemoteServiceService\x12L\n" +
	"\fStartService\x12\x1f.packets.v1.StartServiceRequest\x1a\x1b.packets.v1.ServiceResponse\x12J\n" +
	"\vStopService\x12\x1e.packets.v1.StopServiceRequest\x1a\x1b.packets.v1.ServiceResponse\x12P\n" +
	"\x0eRestartService\x12!.packets.v1.RestartServiceRequest\x1a\x1b.packets.v1.ServiceResponse\x12Q\n" +
	"\fListServices\x12\x1f.packets.v1.ListServicesRequest\x1a .packets.v1.ListServicesResponse\x12W\n" +
	"\x0eGetServiceLogs\x12!.packets.v1.GetServiceLogsRequest\x1a\".packets.v1.GetServiceLogsResponseB-Z+github.com/debaucheryparty/packets/proto/v1b\x06proto3"

var (
	file_proto_v1_service_proto_rawDescOnce sync.Once
	file_proto_v1_service_proto_rawDescData []byte
)

func file_proto_v1_service_proto_rawDescGZIP() []byte {
	file_proto_v1_service_proto_rawDescOnce.Do(func() {
		file_proto_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_service_proto_rawDesc), len(file_proto_v1_service_proto_rawDesc)))
	})
	return file_proto_v1_service_proto_rawDescData
}

var file_proto_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_v1_service_proto_goTypes = []any{
	(*ServiceRecord)(nil),          // 0: packets.v1.ServiceRecord
	(*StartServiceRequest)(nil),    // 1: packets.v1.StartServiceRequest
	(*StopServiceRequest)(nil),     // 2: packets.v1.StopServiceRequest
	(*RestartServiceRequest)(nil),  // 3: packets.v1.RestartServiceRequest
	(*ListServicesRequest)(nil),    // 4: packets.v1.ListServicesRequest
	(*ListServicesResponse)(nil),   // 5: packets.v1.ListServicesResponse
	(*GetServiceLogsRequest)(nil),  // 6: packets.v1.GetServiceLogsRequest
	(*GetServiceLogsResponse)(nil), // 7: packets.v1.GetServiceLogsResponse
	(*ServiceResponse)(nil),        // 8: packets.v1.ServiceResponse
	nil,                            // 9: packets.v1.ServiceRecord.EnvironmentEntry
	nil,                            // 10: packets.v1.StartServiceRequest.EnvironmentEntry
}
var file_proto_v1_service_proto_depIdxs = []int32{
	9,  // 0: packets.v1.ServiceRecord.environment:type_name -> packets.v1.ServiceRecord.EnvironmentEntry
	10, // 1: packets.v1.StartServiceRequest.environment:type_name -> packets.v1.StartServiceRequest.EnvironmentEntry
	0,  // 2: packets.v1.ListServicesResponse.services:type_name -> packets.v1.ServiceRecord
	0,  // 3: packets.v1.ServiceResponse.service:type_name -> packets.v1.ServiceRecord
	1,  // 4: packets.v1.RemoteServiceService.StartService:input_type -> packets.v1.StartServiceRequest
	2,  // 5: packets.v1.RemoteServiceService.StopService:input_type -> packets.v1.StopServiceRequest
	3,  // 6: packets.v1.RemoteServiceService.RestartService:input_type -> packets.v1.RestartServiceRequest
	4,  // 7: packets.v1.RemoteServiceService.ListServices:input_type -> packets.v1.ListServicesRequest
	6,  // 8: packets.v1.RemoteServiceService.GetServiceLogs:input_type -> packets.v1.GetServiceLogsRequest
	8,  // 9: packets.v1.RemoteServiceService.StartService:output_type -> packets.v1.ServiceResponse
	8,  // 10: packets.v1.RemoteServiceService.StopService:output_type -> packets.v1.ServiceResponse
	8,  // 11: packets.v1.RemoteServiceService.RestartService:output_type -> packets.v1.ServiceResponse
	5,  // 12: packets.v1.RemoteServiceService.ListServices:output_type -> packets.v1.ListServicesResponse
	7,  // 13: packets.v1.RemoteServiceService.GetServiceLogs:output_type -> packets.v1.GetServiceLogsResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_v1_service_proto_init() }
func file_proto_v1_service_proto_init() {
	if File_proto_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_service_proto_rawDesc), len(file_proto_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_service_proto_goTypes,
		DependencyIndexes: file_proto_v1_service_proto_depIdxs,
		MessageInfos:      file_proto_v1_service_proto_msgTypes,
	}.Build()
	File_proto_v1_service_proto = out.File
	file_proto_v1_service_proto_goTypes = nil
	file_proto_v1_service_proto_depIdxs = nil
}
