// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: proto/v1/subspace.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubspaceRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	OwnerId       string                 `protobuf:"bytes,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	WorkerId      string                 `protobuf:"bytes,4,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	WorkspaceId   string                 `protobuf:"bytes,5,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	EnvironmentId string                 `protobuf:"bytes,6,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	State         string                 `protobuf:"bytes,7,opt,name=state,proto3" json:"state,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastUsedAt    string                 `protobuf:"bytes,9,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubspaceRecord) Reset() {
	*x = SubspaceRecord{}
	mi := &file_proto_v1_subspace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubspaceRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubspaceRecord) ProtoMessage() {}

func (x *SubspaceRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_subspace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubspaceRecord.ProtoReflect.Descriptor instead.
func (*SubspaceRecord) Descriptor() ([]byte, []int) {
	return file_proto_v1_subspace_proto_rawDescGZIP(), []int{0}
}

func (x *SubspaceRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SubspaceRecord) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *SubspaceRecord) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *SubspaceRecord) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *SubspaceRecord) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *SubspaceRecord) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

func (x *SubspaceRecord) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *SubspaceRecord) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *SubspaceRecord) GetLastUsedAt() string {
	if x != nil {
		return x.LastUsedAt
	}
	return ""
}

func (x *SubspaceRecord) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CreateSubspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	WorkerId      string                 `protobuf:"bytes,3,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	EnvironmentId string                 `protobuf:"bytes,4,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	WorkspaceId   string                 `protobuf:"bytes,5,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSubspaceRequest) Reset() {
	*x = CreateSubspaceRequest{}
	mi := &file_proto_v1_subspace_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubspaceRequest) ProtoMessage() {}

func (x *CreateSubspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_subspace_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubspaceRequest.ProtoReflect.Descriptor instead.
func (*CreateSubspaceRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_subspace_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSubspaceRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreateSubspaceRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *CreateSubspaceRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *CreateSubspaceRequest) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

func (x *CreateSubspaceRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *CreateSubspaceRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GetSubspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubspaceRequest) Reset() {
	*x = GetSubspaceRequest{}
	mi := &file_proto_v1_subspace_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubspaceRequest) ProtoMessage() {}

func (x *GetSubspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_subspace_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubspaceRequest.ProtoReflect.Descriptor instead.
func (*GetSubspaceRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_subspace_proto_rawDescGZIP(), []int{2}
}

func (x *GetSubspaceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListSubspacesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubspacesRequest) Reset() {
	*x = ListSubspacesRequest{}
	mi := &file_proto_v1_subspace_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubspacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubspacesRequest) ProtoMessage() {}

func (x *ListSubspacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_subspace_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubspacesRequest.ProtoReflect.Descriptor instead.
func (*ListSubspacesRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_subspace_proto_rawDescGZIP(), []int{3}
}

func (x *ListSubspacesRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *ListSubspacesRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type ListSubspacesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subspaces     []*SubspaceRecord      `protobuf:"bytes,1,rep,name=subspaces,proto3" json:"subspaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubspacesResponse) Reset() {
	*x = ListSubspacesResponse{}
	mi := &file_proto_v1_subspace_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubspacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubspacesResponse) ProtoMessage() {}

func (x *ListSubspacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_subspace_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubspacesResponse.ProtoReflect.Descriptor instead.
func (*ListSubspacesResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_subspace_proto_rawDescGZIP(), []int{4}
}

func (x *ListSubspacesResponse) GetSubspaces() []*SubspaceRecord {
	if x != nil {
		return x.Subspaces
	}
	return nil
}

type DestroySubspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroySubspaceRequest) Reset() {
	*x = DestroySubspaceRequest{}
	mi := &file_proto_v1_subspace_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroySubspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroySubspaceRequest) ProtoMessage() {}

func (x *DestroySubspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_subspace_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroySubspaceRequest.ProtoReflect.Descriptor instead.
func (*DestroySubspaceRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_subspace_proto_rawDescGZIP(), []int{5}
}

func (x *DestroySubspaceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DestroySubspaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroySubspaceResponse) Reset() {
	*x = DestroySubspaceResponse{}
	mi := &file_proto_v1_subspace_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroySubspaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroySubspaceResponse) ProtoMessage() {}

func (x *DestroySubspaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_subspace_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroySubspaceResponse.ProtoReflect.Descriptor instead.
func (*DestroySubspaceResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_subspace_proto_rawDescGZIP(), []int{6}
}

func (x *DestroySubspaceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type TouchSubspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TouchSubspaceRequest) Reset() {
	*x = TouchSubspaceRequest{}
	mi := &file_proto_v1_subspace_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TouchSubspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TouchSubspaceRequest) ProtoMessage() {}

func (x *TouchSubspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_subspace_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TouchSubspaceRequest.ProtoReflect.Descriptor instead.
func (*TouchSubspaceRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_subspace_proto_rawDescGZIP(), []int{7}
}

func (x *TouchSubspaceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SleepSubspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SleepSubspaceRequest) Reset() {
	*x = SleepSubspaceRequest{}
	mi := &file_proto_v1_subspace_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SleepSubspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SleepSubspaceRequest) ProtoMessage() {}

func (x *SleepSubspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_subspace_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SleepSubspaceRequest.ProtoReflect.Descriptor instead.
func (*SleepSubspaceRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_subspace_proto_rawDescGZIP(), []int{8}
}

func (x *SleepSubspaceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type WakeSubspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WakeSubspaceRequest) Reset() {
	*x = WakeSubspaceRequest{}
	mi := &file_proto_v1_subspace_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WakeSubspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WakeSubspaceRequest) ProtoMessage() {}

func (x *WakeSubspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_subspace_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WakeSubspaceRequest.ProtoReflect.Descriptor instead.
func (*WakeSubspaceRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_subspace_proto_rawDescGZIP(), []int{9}
}

func (x *WakeSubspaceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SubspaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subspace      *SubspaceRecord        `protobuf:"bytes,1,opt,name=subspace,proto3" json:"subspace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubspaceResponse) Reset() {
	*x = SubspaceResponse{}
	mi := &file_proto_v1_subspace_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubspaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubspaceResponse) ProtoMessage() {}

func (x *SubspaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_subspace_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubspaceResponse.ProtoReflect.Descriptor instead.
func (*SubspaceResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_subspace_proto_rawDescGZIP(), []int{10}
}

func (x *SubspaceResponse) GetSubspace() *SubspaceRecord {
	if x != nil {
		return x.Subspace
	}
	return nil
}

var File_proto_v1_subspace_proto protoreflect.FileDescriptor

const file_proto_v1_subspace_proto_rawDesc = "" +
	"\n" +
	"\x17proto/v1/subspace.proto\x12\n" +
	"packets.v1\"\x9b\x03\n" +
	"\x0eSubspaceRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\tR\aownerId\x12\x1b\n" +
	"\tworker_id\x18\x04 \x01(\tR\bworkerId\x12!\n" +
	"\fworkspace_id\x18\x05 \x01(\tR\vworkspaceId\x12%\n" +
	"\x0eenvironment_id\x18\x06 \x01(\tR\renvironmentId\x12\x14\n" +
	"\x05state\x18\a \x01(\tR\x05state\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12 \n" +
	"\flast_used_at\x18\t \x01(\tR\n" +
	"lastUsedAt\x12D\n" +
	"\bmetadata\x18\n" +
	" \x03(\v2(.packets.v1.SubspaceRecord.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc2\x02\n" +
	"\x15CreateSubspaceRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x1b\n" +
	"\tworker_id\x18\x03 \x01(\tR\bworkerId\x12%\n" +
	"\x0eenvironment_id\x18\x04 \x01(\tR\renvironmentId\x12!\n" +
	"\fworkspace_id\x18\x05 \x01(\tR\vworkspaceId\x12K\n" +
	"\bmetadata\x18\x06 \x03(\v2/.packets.v1.CreateSubspaceRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"$\n" +
	"\x12GetSubspaceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"P\n" +
	"\x14ListSubspacesRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\"Q\n" +
	"\x15ListSubspacesResponse\x128\n" +
	"\tsubspaces\x18\x01 \x03(\v2\x1a.packets.v1.SubspaceRecordR\tsubspaces\"(\n" +
	"\x16DestroySubspaceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"3\n" +
	"\x17DestroySubspaceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"&\n" +
	"\x14TouchSubspaceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"&\n" +
	"\x14SleepSubspaceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"%\n" +
	"\x13WakeSubspaceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"J\n" +
	"\x10SubspaceResponse\x126\n" +
	"\bsubspace\x18\x01 \x01(\v2\x1a.packets.v1.SubspaceRecordR\bsubspace2\xd4\x04\n" +
	"\x0fSubspaceService\x12Q\n" +
	"\x0eCreateSubspace\x12!.packets.v1.CreateSubspaceRequest\x1a\x1c.packets.v1.SubspaceResponse\x12K\n" +
	"\vGetSubspace\x12\x1e.packets.v1.GetSubspaceRequest\x1a\x1c.packets.v1.SubspaceResponse\x12T\n" +
	"\rListSubspaces\x12 .packets.v1.ListSubspacesRequest\x1a!.packets.v1.ListSubspacesResponse\x12Z\n" +
	"\x0fDestroySubspace\x12\".packets.v1.DestroySubspaceRequest\x1a#.packets.v1.DestroySubspaceResponse\x12O\n" +
	"\rTouchSubspace\x12 .packets.v1.TouchSubspaceRequest\x1a\x1c.packets.v1.SubspaceResponse\x12O\n" +
	"\rSleepSubspace\x12 .packets.v1.SleepSubspaceRequest\x1a\x1c.packets.v1.SubspaceResponse\x12M\n" +
	"\fWakeSubspace\x12\x1f.packets.v1.WakeSubspaceRequest\x1a\x1c.packets.v1.SubspaceResponseB-Z+github.com/debaucheryparty/packets/proto/v1b\x06proto3"

var (
	file_proto_v1_subspace_proto_rawDescOnce sync.Once
	file_proto_v1_subspace_proto_rawDescData []byte
)

func file_proto_v1_subspace_proto_rawDescGZIP() []byte {
	file_proto_v1_subspace_proto_rawDescOnce.Do(func() {
		file_proto_v1_subspace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_subspace_proto_rawDesc), len(file_proto_v1_subspace_proto_rawDesc)))
	})
	return file_proto_v1_subspace_proto_rawDescData
}

var file_proto_v1_subspace_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_v1_subspace_proto_goTypes = []any{
	(*SubspaceRecord)(nil),          // 0: packets.v1.SubspaceRecord
	(*CreateSubspaceRequest)(nil),   // 1: packets.v1.CreateSubspaceRequest
	(*GetSubspaceRequest)(nil),      // 2: packets.v1.GetSubspaceRequest
	(*ListSubspacesRequest)(nil),    // 3: packets.v1.ListSubspacesRequest
	(*ListSubspacesResponse)(nil),   // 4: packets.v1.ListSubspacesResponse
	(*DestroySubspaceRequest)(nil),  // 5: packets.v1.DestroySubspaceRequest
	(*DestroySubspaceResponse)(nil), // 6: packets.v1.DestroySubspaceResponse
	(*TouchSubspaceRequest)(nil),    // 7: packets.v1.TouchSubspaceRequest
	(*SleepSubspaceRequest)(nil),    // 8: packets.v1.SleepSubspaceRequest
	(*WakeSubspaceRequest)(nil),     // 9: packets.v1.WakeSubspaceRequest
	(*SubspaceResponse)(nil),        // 10: packets.v1.SubspaceResponse
	nil,                             // 11: packets.v1.SubspaceRecord.MetadataEntry
	nil,                             // 12: packets.v1.CreateSubspaceRequest.MetadataEntry
}
var file_proto_v1_subspace_proto_depIdxs = []int32{
	11, // 0: packets.v1.SubspaceRecord.metadata:type_name -> packets.v1.SubspaceRecord.MetadataEntry
	12, // 1: packets.v1.CreateSubspaceRequest.metadata:type_name -> packets.v1.CreateSubspaceRequest.MetadataEntry
	0,  // 2: packets.v1.ListSubspacesResponse.subspaces:type_name -> packets.v1.SubspaceRecord
	0,  // 3: packets.v1.SubspaceResponse.subspace:type_name -> packets.v1.SubspaceRecord
	1,  // 4: packets.v1.SubspaceService.CreateSubspace:input_type -> packets.v1.CreateSubspaceRequest
	2,  // 5: packets.v1.SubspaceService.GetSubspace:input_type -> packets.v1.GetSubspaceRequest
	3,  // 6: packets.v1.SubspaceService.ListSubspaces:input_type -> packets.v1.ListSubspacesRequest
	5,  // 7: packets.v1.SubspaceService.DestroySubspace:input_type -> packets.v1.DestroySubspaceRequest
	7,  // 8: packets.v1.SubspaceService.TouchSubspace:input_type -> packets.v1.TouchSubspaceRequest
	8,  // 9: packets.v1.SubspaceService.SleepSubspace:input_type -> packets.v1.SleepSubspaceRequest
	9,  // 10: packets.v1.SubspaceService.WakeSubspace:input_type -> packets.v1.WakeSubspaceRequest
	10, // 11: packets.v1.SubspaceService.CreateSubspace:output_type -> packets.v1.SubspaceResponse
	10, // 12: packets.v1.SubspaceService.GetSubspace:output_type -> packets.v1.SubspaceResponse
	4,  // 13: packets.v1.SubspaceService.ListSubspaces:output_type -> packets.v1.ListSubspacesResponse
	6,  // 14: packets.v1.SubspaceService.DestroySubspace:output_type -> packets.v1.DestroySubspaceResponse
	10, // 15: packets.v1.SubspaceService.TouchSubspace:output_type -> packets.v1.SubspaceResponse
	10, // 16: packets.v1.SubspaceService.SleepSubspace:output_type -> packets.v1.SubspaceResponse
	10, // 17: packets.v1.SubspaceService.WakeSubspace:output_type -> packets.v1.SubspaceResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_v1_subspace_proto_init() }
func file_proto_v1_subspace_proto_init() {
	if File_proto_v1_subspace_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_subspace_proto_rawDesc), len(file_proto_v1_subspace_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_subspace_proto_goTypes,
		DependencyIndexes: file_proto_v1_subspace_proto_depIdxs,
		MessageInfos:      file_proto_v1_subspace_proto_msgTypes,
	}.Build()
	File_proto_v1_subspace_proto = out.File
	file_proto_v1_subspace_proto_goTypes = nil
	file_proto_v1_subspace_proto_depIdxs = nil
}
