// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: proto/v1/subspace.proto

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SubspaceService_CreateSubspace_FullMethodName  = "/packets.v1.SubspaceService/CreateSubspace"
	SubspaceService_GetSubspace_FullMethodName     = "/packets.v1.SubspaceService/GetSubspace"
	SubspaceService_ListSubspaces_FullMethodName   = "/packets.v1.SubspaceService/ListSubspaces"
	SubspaceService_DestroySubspace_FullMethodName = "/packets.v1.SubspaceService/DestroySubspace"
	SubspaceService_TouchSubspace_FullMethodName   = "/packets.v1.SubspaceService/TouchSubspace"
)

// SubspaceServiceClient is the client API for SubspaceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SubspaceServiceClient interface {
	CreateSubspace(ctx context.Context, in *CreateSubspaceRequest, opts ...grpc.CallOption) (*SubspaceResponse, error)
	GetSubspace(ctx context.Context, in *GetSubspaceRequest, opts ...grpc.CallOption) (*SubspaceResponse, error)
	ListSubspaces(ctx context.Context, in *ListSubspacesRequest, opts ...grpc.CallOption) (*ListSubspacesResponse, error)
	DestroySubspace(ctx context.Context, in *DestroySubspaceRequest, opts ...grpc.CallOption) (*DestroySubspaceResponse, error)
	TouchSubspace(ctx context.Context, in *TouchSubspaceRequest, opts ...grpc.CallOption) (*SubspaceResponse, error)
}

type subspaceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSubspaceServiceClient(cc grpc.ClientConnInterface) SubspaceServiceClient {
	return &subspaceServiceClient{cc}
}

func (c *subspaceServiceClient) CreateSubspace(ctx context.Context, in *CreateSubspaceRequest, opts ...grpc.CallOption) (*SubspaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubspaceResponse)
	err := c.cc.Invoke(ctx, SubspaceService_CreateSubspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subspaceServiceClient) GetSubspace(ctx context.Context, in *GetSubspaceRequest, opts ...grpc.CallOption) (*SubspaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubspaceResponse)
	err := c.cc.Invoke(ctx, SubspaceService_GetSubspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subspaceServiceClient) ListSubspaces(ctx context.Context, in *ListSubspacesRequest, opts ...grpc.CallOption) (*ListSubspacesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSubspacesResponse)
	err := c.cc.Invoke(ctx, SubspaceService_ListSubspaces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subspaceServiceClient) DestroySubspace(ctx context.Context, in *DestroySubspaceRequest, opts ...grpc.CallOption) (*DestroySubspaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DestroySubspaceResponse)
	err := c.cc.Invoke(ctx, SubspaceService_DestroySubspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subspaceServiceClient) TouchSubspace(ctx context.Context, in *TouchSubspaceRequest, opts ...grpc.CallOption) (*SubspaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubspaceResponse)
	err := c.cc.Invoke(ctx, SubspaceService_TouchSubspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubspaceServiceServer is the server API for SubspaceService service.
// All implementations must embed UnimplementedSubspaceServiceServer
// for forward compatibility.
type SubspaceServiceServer interface {
	CreateSubspace(context.Context, *CreateSubspaceRequest) (*SubspaceResponse, error)
	GetSubspace(context.Context, *GetSubspaceRequest) (*SubspaceResponse, error)
	ListSubspaces(context.Context, *ListSubspacesRequest) (*ListSubspacesResponse, error)
	DestroySubspace(context.Context, *DestroySubspaceRequest) (*DestroySubspaceResponse, error)
	TouchSubspace(context.Context, *TouchSubspaceRequest) (*SubspaceResponse, error)
	mustEmbedUnimplementedSubspaceServiceServer()
}

// UnimplementedSubspaceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSubspaceServiceServer struct{}

func (UnimplementedSubspaceServiceServer) CreateSubspace(context.Context, *CreateSubspaceRequest) (*SubspaceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSubspace not implemented")
}

func (UnimplementedSubspaceServiceServer) GetSubspace(context.Context, *GetSubspaceRequest) (*SubspaceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSubspace not implemented")
}

func (UnimplementedSubspaceServiceServer) ListSubspaces(context.Context, *ListSubspacesRequest) (*ListSubspacesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSubspaces not implemented")
}

func (UnimplementedSubspaceServiceServer) DestroySubspace(context.Context, *DestroySubspaceRequest) (*DestroySubspaceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DestroySubspace not implemented")
}

func (UnimplementedSubspaceServiceServer) TouchSubspace(context.Context, *TouchSubspaceRequest) (*SubspaceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TouchSubspace not implemented")
}
func (UnimplementedSubspaceServiceServer) mustEmbedUnimplementedSubspaceServiceServer() {}
func (UnimplementedSubspaceServiceServer) testEmbeddedByValue()                         {}

// UnsafeSubspaceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubspaceServiceServer will
// result in compilation errors.
type UnsafeSubspaceServiceServer interface {
	mustEmbedUnimplementedSubspaceServiceServer()
}

func RegisterSubspaceServiceServer(s grpc.ServiceRegistrar, srv SubspaceServiceServer) {
	// If the following call panics, it indicates UnimplementedSubspaceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SubspaceService_ServiceDesc, srv)
}

func _SubspaceService_CreateSubspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSubspaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubspaceServiceServer).CreateSubspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubspaceService_CreateSubspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubspaceServiceServer).CreateSubspace(ctx, req.(*CreateSubspaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubspaceService_GetSubspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubspaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubspaceServiceServer).GetSubspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubspaceService_GetSubspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubspaceServiceServer).GetSubspace(ctx, req.(*GetSubspaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubspaceService_ListSubspaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSubspacesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubspaceServiceServer).ListSubspaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubspaceService_ListSubspaces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubspaceServiceServer).ListSubspaces(ctx, req.(*ListSubspacesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubspaceService_DestroySubspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroySubspaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubspaceServiceServer).DestroySubspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubspaceService_DestroySubspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubspaceServiceServer).DestroySubspace(ctx, req.(*DestroySubspaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubspaceService_TouchSubspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TouchSubspaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubspaceServiceServer).TouchSubspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubspaceService_TouchSubspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubspaceServiceServer).TouchSubspace(ctx, req.(*TouchSubspaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SubspaceService_ServiceDesc is the grpc.ServiceDesc for SubspaceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SubspaceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "packets.v1.SubspaceService",
	HandlerType: (*SubspaceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSubspace",
			Handler:    _SubspaceService_CreateSubspace_Handler,
		},
		{
			MethodName: "GetSubspace",
			Handler:    _SubspaceService_GetSubspace_Handler,
		},
		{
			MethodName: "ListSubspaces",
			Handler:    _SubspaceService_ListSubspaces_Handler,
		},
		{
			MethodName: "DestroySubspace",
			Handler:    _SubspaceService_DestroySubspace_Handler,
		},
		{
			MethodName: "TouchSubspace",
			Handler:    _SubspaceService_TouchSubspace_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/v1/subspace.proto",
}
