// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: proto/v1/transaction.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionRecord struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId          string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	SubspaceId         string                 `protobuf:"bytes,3,opt,name=subspace_id,json=subspaceId,proto3" json:"subspace_id,omitempty"`
	BaseSnapshotRef    string                 `protobuf:"bytes,4,opt,name=base_snapshot_ref,json=baseSnapshotRef,proto3" json:"base_snapshot_ref,omitempty"`
	WorkingSnapshotRef string                 `protobuf:"bytes,5,opt,name=working_snapshot_ref,json=workingSnapshotRef,proto3" json:"working_snapshot_ref,omitempty"`
	Status             string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Description        string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt          string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TransactionRecord) Reset() {
	*x = TransactionRecord{}
	mi := &file_proto_v1_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionRecord) ProtoMessage() {}

func (x *TransactionRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionRecord.ProtoReflect.Descriptor instead.
func (*TransactionRecord) Descriptor() ([]byte, []int) {
	return file_proto_v1_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TransactionRecord) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *TransactionRecord) GetSubspaceId() string {
	if x != nil {
		return x.SubspaceId
	}
	return ""
}

func (x *TransactionRecord) GetBaseSnapshotRef() string {
	if x != nil {
		return x.BaseSnapshotRef
	}
	return ""
}

func (x *TransactionRecord) GetWorkingSnapshotRef() string {
	if x != nil {
		return x.WorkingSnapshotRef
	}
	return ""
}

func (x *TransactionRecord) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TransactionRecord) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TransactionRecord) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *TransactionRecord) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreateTransactionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProjectId       string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	SubspaceId      string                 `protobuf:"bytes,2,opt,name=subspace_id,json=subspaceId,proto3" json:"subspace_id,omitempty"`
	BaseSnapshotRef string                 `protobuf:"bytes,3,opt,name=base_snapshot_ref,json=baseSnapshotRef,proto3" json:"base_snapshot_ref,omitempty"`
	Description     string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateTransactionRequest) Reset() {
	*x = CreateTransactionRequest{}
	mi := &file_proto_v1_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionRequest) ProtoMessage() {}

func (x *CreateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionRequest.ProtoReflect.Descriptor instead.
func (*CreateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTransactionRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreateTransactionRequest) GetSubspaceId() string {
	if x != nil {
		return x.SubspaceId
	}
	return ""
}

func (x *CreateTransactionRequest) GetBaseSnapshotRef() string {
	if x != nil {
		return x.BaseSnapshotRef
	}
	return ""
}

func (x *CreateTransactionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GetTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionRequest) Reset() {
	*x = GetTransactionRequest{}
	mi := &file_proto_v1_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionRequest) ProtoMessage() {}

func (x *GetTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *GetTransactionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CommitTransactionRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WorkingSnapshotRef string                 `protobuf:"bytes,2,opt,name=working_snapshot_ref,json=workingSnapshotRef,proto3" json:"working_snapshot_ref,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CommitTransactionRequest) Reset() {
	*x = CommitTransactionRequest{}
	mi := &file_proto_v1_transaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitTransactionRequest) ProtoMessage() {}

func (x *CommitTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_transaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitTransactionRequest.ProtoReflect.Descriptor instead.
func (*CommitTransactionRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_transaction_proto_rawDescGZIP(), []int{3}
}

func (x *CommitTransactionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CommitTransactionRequest) GetWorkingSnapshotRef() string {
	if x != nil {
		return x.WorkingSnapshotRef
	}
	return ""
}

type RollbackTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackTransactionRequest) Reset() {
	*x = RollbackTransactionRequest{}
	mi := &file_proto_v1_transaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackTransactionRequest) ProtoMessage() {}

func (x *RollbackTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_transaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackTransactionRequest.ProtoReflect.Descriptor instead.
func (*RollbackTransactionRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_transaction_proto_rawDescGZIP(), []int{4}
}

func (x *RollbackTransactionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionsRequest) Reset() {
	*x = ListTransactionsRequest{}
	mi := &file_proto_v1_transaction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsRequest) ProtoMessage() {}

func (x *ListTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_transaction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsRequest.ProtoReflect.Descriptor instead.
func (*ListTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_transaction_proto_rawDescGZIP(), []int{5}
}

func (x *ListTransactionsRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type ListTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*TransactionRecord   `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionsResponse) Reset() {
	*x = ListTransactionsResponse{}
	mi := &file_proto_v1_transaction_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsResponse) ProtoMessage() {}

func (x *ListTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_transaction_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsResponse.ProtoReflect.Descriptor instead.
func (*ListTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_transaction_proto_rawDescGZIP(), []int{6}
}

func (x *ListTransactionsResponse) GetTransactions() []*TransactionRecord {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type TransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *TransactionRecord     `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionResponse) Reset() {
	*x = TransactionResponse{}
	mi := &file_proto_v1_transaction_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionResponse) ProtoMessage() {}

func (x *TransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_transaction_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionResponse.ProtoReflect.Descriptor instead.
func (*TransactionResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_transaction_proto_rawDescGZIP(), []int{7}
}

func (x *TransactionResponse) GetTransaction() *TransactionRecord {
	if x != nil {
		return x.Transaction
	}
	return nil
}

var File_proto_v1_transaction_proto protoreflect.FileDescriptor

const file_proto_v1_transaction_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/v1/transaction.proto\x12\n" +
	"packets.v1\"\xb9\x02\n" +
	"\x11TransactionRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x1f\n" +
	"\vsubspace_id\x18\x03 \x01(\tR\n" +
	"subspaceId\x12*\n" +
	"\x11base_snapshot_ref\x18\x04 \x01(\tR\x0fbaseSnapshotRef\x120\n" +
	"\x14working_snapshot_ref\x18\x05 \x01(\tR\x12workingSnapshotRef\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\"\xa8\x01\n" +
	"\x18CreateTransactionRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x1f\n" +
	"\vsubspace_id\x18\x02 \x01(\tR\n" +
	"subspaceId\x12*\n" +
	"\x11base_snapshot_ref\x18\x03 \x01(\tR\x0fbaseSnapshotRef\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"'\n" +
	"\x15GetTransactionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\\\n" +
	"\x18CommitTransactionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x120\n" +
	"\x14working_snapshot_ref\x18\x02 \x01(\tR\x12workingSnapshotRef\",\n" +
	"\x1aRollbackTransactionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"8\n" +
	"\x17ListTransactionsRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\"]\n" +
	"\x18ListTransactionsResponse\x12A\n" +
	"\ftransactions\x18\x01 \x03(\v2\x1d.packets.v1.TransactionRecordR\ftransactions\"V\n" +
	"\x13TransactionResponse\x12?\n" +
	"\vtransaction\x18\x01 \x01(\v2\x1d.packets.v1.TransactionRecordR\vtransaction2\xe1\x03\n" +
	"\x12TransactionService\x12Z\n" +
	"\x11CreateTransaction\x12$.packets.v1.CreateTransactionRequest\x1a\x1f.packets.v1.TransactionResponse\x12T\n" +
	"\x0eGetTransaction\x12!.packets.v1.GetTransactionRequest\x1a\x1f.packets.v1.TransactionResponse\x12Z\n" +
	"\x11CommitTransaction\x12$.packets.v1.CommitTransactionRequest\x1a\x1f.packets.v1.TransactionResponse\x12^\n" +
	"\x13RollbackTransaction\x12&.packets.v1.RollbackTransactionRequest\x1a\x1f.packets.v1.TransactionResponse\x12]\n" +
	"\x10ListTransactions\x12#.packets.v1.ListTransactionsRequest\x1a$.packets.v1.ListTransactionsResponseB-Z+github.com/debaucheryparty/packets/proto/v1b\x06proto3"

var (
	file_proto_v1_transaction_proto_rawDescOnce sync.Once
	file_proto_v1_transaction_proto_rawDescData []byte
)

func file_proto_v1_transaction_proto_rawDescGZIP() []byte {
	file_proto_v1_transaction_proto_rawDescOnce.Do(func() {
		file_proto_v1_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_transaction_proto_rawDesc), len(file_proto_v1_transaction_proto_rawDesc)))
	})
	return file_proto_v1_transaction_proto_rawDescData
}

var file_proto_v1_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_v1_transaction_proto_goTypes = []any{
	(*TransactionRecord)(nil),          // 0: packets.v1.TransactionRecord
	(*CreateTransactionRequest)(nil),   // 1: packets.v1.CreateTransactionRequest
	(*GetTransactionRequest)(nil),      // 2: packets.v1.GetTransactionRequest
	(*CommitTransactionRequest)(nil),   // 3: packets.v1.CommitTransactionRequest
	(*RollbackTransactionRequest)(nil), // 4: packets.v1.RollbackTransactionRequest
	(*ListTransactionsRequest)(nil),    // 5: packets.v1.ListTransactionsRequest
	(*ListTransactionsResponse)(nil),   // 6: packets.v1.ListTransactionsResponse
	(*TransactionResponse)(nil),        // 7: packets.v1.TransactionResponse
}
var file_proto_v1_transaction_proto_depIdxs = []int32{
	0, // 0: packets.v1.ListTransactionsResponse.transactions:type_name -> packets.v1.TransactionRecord
	0, // 1: packets.v1.TransactionResponse.transaction:type_name -> packets.v1.TransactionRecord
	1, // 2: packets.v1.TransactionService.CreateTransaction:input_type -> packets.v1.CreateTransactionRequest
	2, // 3: packets.v1.TransactionService.GetTransaction:input_type -> packets.v1.GetTransactionRequest
	3, // 4: packets.v1.TransactionService.CommitTransaction:input_type -> packets.v1.CommitTransactionRequest
	4, // 5: packets.v1.TransactionService.RollbackTransaction:input_type -> packets.v1.RollbackTransactionRequest
	5, // 6: packets.v1.TransactionService.ListTransactions:input_type -> packets.v1.ListTransactionsRequest
	7, // 7: packets.v1.TransactionService.CreateTransaction:output_type -> packets.v1.TransactionResponse
	7, // 8: packets.v1.TransactionService.GetTransaction:output_type -> packets.v1.TransactionResponse
	7, // 9: packets.v1.TransactionService.CommitTransaction:output_type -> packets.v1.TransactionResponse
	7, // 10: packets.v1.TransactionService.RollbackTransaction:output_type -> packets.v1.TransactionResponse
	6, // 11: packets.v1.TransactionService.ListTransactions:output_type -> packets.v1.ListTransactionsResponse
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_v1_transaction_proto_init() }
func file_proto_v1_transaction_proto_init() {
	if File_proto_v1_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_transaction_proto_rawDesc), len(file_proto_v1_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_transaction_proto_goTypes,
		DependencyIndexes: file_proto_v1_transaction_proto_depIdxs,
		MessageInfos:      file_proto_v1_transaction_proto_msgTypes,
	}.Build()
	File_proto_v1_transaction_proto = out.File
	file_proto_v1_transaction_proto_goTypes = nil
	file_proto_v1_transaction_proto_depIdxs = nil
}
