// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: proto/v1/workspace.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkspaceManifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootHash      string                 `protobuf:"bytes,1,opt,name=root_hash,json=rootHash,proto3" json:"root_hash,omitempty"`
	Files         []*FileEntry           `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceManifest) Reset() {
	*x = WorkspaceManifest{}
	mi := &file_proto_v1_workspace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceManifest) ProtoMessage() {}

func (x *WorkspaceManifest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_workspace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceManifest.ProtoReflect.Descriptor instead.
func (*WorkspaceManifest) Descriptor() ([]byte, []int) {
	return file_proto_v1_workspace_proto_rawDescGZIP(), []int{0}
}

func (x *WorkspaceManifest) GetRootHash() string {
	if x != nil {
		return x.RootHash
	}
	return ""
}

func (x *WorkspaceManifest) GetFiles() []*FileEntry {
	if x != nil {
		return x.Files
	}
	return nil
}

type FileEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Hash          string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Mode          uint32                 `protobuf:"varint,4,opt,name=mode,proto3" json:"mode,omitempty"`
	IsDir         bool                   `protobuf:"varint,5,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Link          string                 `protobuf:"bytes,6,opt,name=link,proto3" json:"link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileEntry) Reset() {
	*x = FileEntry{}
	mi := &file_proto_v1_workspace_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileEntry) ProtoMessage() {}

func (x *FileEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_workspace_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileEntry.ProtoReflect.Descriptor instead.
func (*FileEntry) Descriptor() ([]byte, []int) {
	return file_proto_v1_workspace_proto_rawDescGZIP(), []int{1}
}

func (x *FileEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileEntry) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *FileEntry) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileEntry) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *FileEntry) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *FileEntry) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

type DiffResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	MissingHashes       []string               `protobuf:"bytes,1,rep,name=missing_hashes,json=missingHashes,proto3" json:"missing_hashes,omitempty"`
	PresignedPutUrls    map[string]string      `protobuf:"bytes,2,rep,name=presigned_put_urls,json=presignedPutUrls,proto3" json:"presigned_put_urls,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ExistingSnapshotRef string                 `protobuf:"bytes,3,opt,name=existing_snapshot_ref,json=existingSnapshotRef,proto3" json:"existing_snapshot_ref,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DiffResponse) Reset() {
	*x = DiffResponse{}
	mi := &file_proto_v1_workspace_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffResponse) ProtoMessage() {}

func (x *DiffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_workspace_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffResponse.ProtoReflect.Descriptor instead.
func (*DiffResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_workspace_proto_rawDescGZIP(), []int{2}
}

func (x *DiffResponse) GetMissingHashes() []string {
	if x != nil {
		return x.MissingHashes
	}
	return nil
}

func (x *DiffResponse) GetPresignedPutUrls() map[string]string {
	if x != nil {
		return x.PresignedPutUrls
	}
	return nil
}

func (x *DiffResponse) GetExistingSnapshotRef() string {
	if x != nil {
		return x.ExistingSnapshotRef
	}
	return ""
}

type CommitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootHash      string                 `protobuf:"bytes,1,opt,name=root_hash,json=rootHash,proto3" json:"root_hash,omitempty"`
	Files         []*FileEntry           `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	Toolchain     string                 `protobuf:"bytes,3,opt,name=toolchain,proto3" json:"toolchain,omitempty"`
	Runner        string                 `protobuf:"bytes,4,opt,name=runner,proto3" json:"runner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitRequest) Reset() {
	*x = CommitRequest{}
	mi := &file_proto_v1_workspace_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitRequest) ProtoMessage() {}

func (x *CommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_workspace_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitRequest.ProtoReflect.Descriptor instead.
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_workspace_proto_rawDescGZIP(), []int{3}
}

func (x *CommitRequest) GetRootHash() string {
	if x != nil {
		return x.RootHash
	}
	return ""
}

func (x *CommitRequest) GetFiles() []*FileEntry {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *CommitRequest) GetToolchain() string {
	if x != nil {
		return x.Toolchain
	}
	return ""
}

func (x *CommitRequest) GetRunner() string {
	if x != nil {
		return x.Runner
	}
	return ""
}

type CommitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnapshotRef   string                 `protobuf:"bytes,1,opt,name=snapshot_ref,json=snapshotRef,proto3" json:"snapshot_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitResponse) Reset() {
	*x = CommitResponse{}
	mi := &file_proto_v1_workspace_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitResponse) ProtoMessage() {}

func (x *CommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_workspace_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitResponse.ProtoReflect.Descriptor instead.
func (*CommitResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_workspace_proto_rawDescGZIP(), []int{4}
}

func (x *CommitResponse) GetSnapshotRef() string {
	if x != nil {
		return x.SnapshotRef
	}
	return ""
}

type WorkspaceChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceChunk) Reset() {
	*x = WorkspaceChunk{}
	mi := &file_proto_v1_workspace_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceChunk) ProtoMessage() {}

func (x *WorkspaceChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_workspace_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceChunk.ProtoReflect.Descriptor instead.
func (*WorkspaceChunk) Descriptor() ([]byte, []int) {
	return file_proto_v1_workspace_proto_rawDescGZIP(), []int{5}
}

func (x *WorkspaceChunk) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type DownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnapshotRef   string                 `protobuf:"bytes,1,opt,name=snapshot_ref,json=snapshotRef,proto3" json:"snapshot_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadRequest) Reset() {
	*x = DownloadRequest{}
	mi := &file_proto_v1_workspace_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadRequest) ProtoMessage() {}

func (x *DownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_workspace_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadRequest.ProtoReflect.Descriptor instead.
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_workspace_proto_rawDescGZIP(), []int{6}
}

func (x *DownloadRequest) GetSnapshotRef() string {
	if x != nil {
		return x.SnapshotRef
	}
	return ""
}

var File_proto_v1_workspace_proto protoreflect.FileDescriptor

const file_proto_v1_workspace_proto_rawDesc = "" +
	"\n" +
	"\x18proto/v1/workspace.proto\x12\n" +
	"packets.v1\"]\n" +
	"\x11WorkspaceManifest\x12\x1b\n" +
	"\troot_hash\x18\x01 \x01(\tR\brootHash\x12+\n" +
	"\x05files\x18\x02 \x03(\v2\x15.packets.v1.FileEntryR\x05files\"\x86\x01\n" +
	"\tFileEntry\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\rR\x04mode\x12\x15\n" +
	"\x06is_dir\x18\x05 \x01(\bR\x05isDir\x12\x12\n" +
	"\x04link\x18\x06 \x01(\tR\x04link\"\x8c\x02\n" +
	"\fDiffResponse\x12%\n" +
	"\x0emissing_hashes\x18\x01 \x03(\tR\rmissingHashes\x12\\\n" +
	"\x12presigned_put_urls\x18\x02 \x03(\v2..packets.v1.DiffResponse.PresignedPutUrlsEntryR\x10presignedPutUrls\x122\n" +
	"\x15existing_snapshot_ref\x18\x03 \x01(\tR\x13existingSnapshotRef\x1aC\n" +
	"\x15PresignedPutUrlsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8f\x01\n" +
	"\rCommitRequest\x12\x1b\n" +
	"\troot_hash\x18\x01 \x01(\tR\brootHash\x12+\n" +
	"\x05files\x18\x02 \x03(\v2\x15.packets.v1.FileEntryR\x05files\x12\x1c\n" +
	"\ttoolchain\x18\x03 \x01(\tR\ttoolchain\x12\x16\n" +
	"\x06runner\x18\x04 \x01(\tR\x06runner\"3\n" +
	"\x0eCommitResponse\x12!\n" +
	"\fsnapshot_ref\x18\x01 \x01(\tR\vsnapshotRef\"&\n" +
	"\x0eWorkspaceChunk\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk\"4\n" +
	"\x0fDownloadRequest\x12!\n" +
	"\fsnapshot_ref\x18\x01 \x01(\tR\vsnapshotRef2\xd4\x01\n" +
	"\tWorkspace\x12?\n" +
	"\x04Diff\x12\x1d.packets.v1.WorkspaceManifest\x1a\x18.packets.v1.DiffResponse\x12?\n" +
	"\x06Commit\x12\x19.packets.v1.CommitRequest\x1a\x1a.packets.v1.CommitResponse\x12E\n" +
	"\bSnapshot\x12\x1b.packets.v1.DownloadRequest\x1a\x1a.packets.v1.WorkspaceChunk0\x01B&Z$github.com/waris4ly/packets/proto/v1b\x06proto3"

var (
	file_proto_v1_workspace_proto_rawDescOnce sync.Once
	file_proto_v1_workspace_proto_rawDescData []byte
)

func file_proto_v1_workspace_proto_rawDescGZIP() []byte {
	file_proto_v1_workspace_proto_rawDescOnce.Do(func() {
		file_proto_v1_workspace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_workspace_proto_rawDesc), len(file_proto_v1_workspace_proto_rawDesc)))
	})
	return file_proto_v1_workspace_proto_rawDescData
}

var file_proto_v1_workspace_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_v1_workspace_proto_goTypes = []any{
	(*WorkspaceManifest)(nil), // 0: packets.v1.WorkspaceManifest
	(*FileEntry)(nil),         // 1: packets.v1.FileEntry
	(*DiffResponse)(nil),      // 2: packets.v1.DiffResponse
	(*CommitRequest)(nil),     // 3: packets.v1.CommitRequest
	(*CommitResponse)(nil),    // 4: packets.v1.CommitResponse
	(*WorkspaceChunk)(nil),    // 5: packets.v1.WorkspaceChunk
	(*DownloadRequest)(nil),   // 6: packets.v1.DownloadRequest
	nil,                       // 7: packets.v1.DiffResponse.PresignedPutUrlsEntry
}
var file_proto_v1_workspace_proto_depIdxs = []int32{
	1, // 0: packets.v1.WorkspaceManifest.files:type_name -> packets.v1.FileEntry
	7, // 1: packets.v1.DiffResponse.presigned_put_urls:type_name -> packets.v1.DiffResponse.PresignedPutUrlsEntry
	1, // 2: packets.v1.CommitRequest.files:type_name -> packets.v1.FileEntry
	0, // 3: packets.v1.Workspace.Diff:input_type -> packets.v1.WorkspaceManifest
	3, // 4: packets.v1.Workspace.Commit:input_type -> packets.v1.CommitRequest
	6, // 5: packets.v1.Workspace.Snapshot:input_type -> packets.v1.DownloadRequest
	2, // 6: packets.v1.Workspace.Diff:output_type -> packets.v1.DiffResponse
	4, // 7: packets.v1.Workspace.Commit:output_type -> packets.v1.CommitResponse
	5, // 8: packets.v1.Workspace.Snapshot:output_type -> packets.v1.WorkspaceChunk
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_v1_workspace_proto_init() }
func file_proto_v1_workspace_proto_init() {
	if File_proto_v1_workspace_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_workspace_proto_rawDesc), len(file_proto_v1_workspace_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_workspace_proto_goTypes,
		DependencyIndexes: file_proto_v1_workspace_proto_depIdxs,
		MessageInfos:      file_proto_v1_workspace_proto_msgTypes,
	}.Build()
	File_proto_v1_workspace_proto = out.File
	file_proto_v1_workspace_proto_goTypes = nil
	file_proto_v1_workspace_proto_depIdxs = nil
}
